apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paas-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://level3.git.onstackit.cloud/LEVEL3/Moheddine.git
    targetRevision: main
    path: week-4/gitops/paas-service/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true