---
- name: Check if this node already joined a cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join the cluster
  command: "{{ hostvars[groups['control_plane'][0]]['join_command'] }}"
  when: not kubelet_conf.stat.exists