apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: cnpg-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: moheddinebelha@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            solverName: stackit
            groupName: acme.stackit.de
            config:
              projectId: 4b7cad06-1e47-46b9-ad28-5e18efd87552